#!perl

# DATE
# VERSION

use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::cryp;

my $prefix = '/App/cryp/arbit/';

$ENV{LOG_ADD_TIMESTAMP} //= 1;
Perinci::CmdLine::cryp->new(
    url => $prefix,
    log => 1,
    pass_cmdline_object => 1,
    config_filename => ["cryp.conf", "cryp-arbit.conf"],
    subcommands => {
        "dump-cryp-config" => { url=>"${prefix}dump_cryp_config" },
        arbit => { url=>"${prefix}arbit" },
        opportunities => { url=>"${prefix}show_opportunities" },
        'check-orders' => { url=>"${prefix}check_orders" },
        'order-pairs' => { url=>"${prefix}list_order_pairs" },
        'profit-report' => { url=>"${prefix}get_profit_report" },
    },
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

In F<~/.config/cryp-arbit.conf> (or F<~/.config/cryp.conf> as the configuration
can be shared between cryp-* family of scripts):

 [program=cryp-arbit]
 db_name = cryp_arbit
 ; db_username = youruser         ; optional, will be searched in ~/.my.cnf
 ; db_password = yourpass         ; optional, will be searched in ~/.my.cnf

 [exchange/indodax]
 key = ...
 secret = ...

 [exchange/gdax]
 key = ...
 secret = ...
 passphrase = ...

Then to test:

 % cryp-arbit opportunities
 % cryp-arbit arbit --debug --dry-run

To really create sell/buy orders:

 % cryp-arbit arbit

To list created order pairs:

 % cryp-arbit order-pairs
 % cryp-arbit order-pairs --open

To check the status of created orders (and cancel orders that are not being
filled for too long):

 % cryp-arbit check-orders

To get profit report:

 % cryp-arbit profit-report

 # Use specified USD spot rates (e.g. USD/IDR=14500, USD/THB=33.25)
 % cryp-arbit profit-report --usd-rate IDR=14500 --usd-rate THB=33.25

For other subcommands, use C<cryp-arbit --help> or see the documentation.


=head1 DESCRIPTION


=head1 SEE ALSO

Other scripts in the C<cryp-*> family.
